AWSTemplateFormatVersion: '2010-09-09'

Description: Authentication for techytechster.com

Resources:
  AdminUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: admin_only
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: True
      AliasAttributes:
        - phone_number
        - email
        - preferred_username
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: True
        DeviceOnlyRememberedOnUserPrompt: True
      MfaConfiguration: "OFF" # MFA cost money, and I'm poor
      UserPoolName: "AdminUserPool"
  AdminLoginClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref AdminUserPool
      CallbackURLs:
        - http://localhost:3000
        - https://admin.techytechster.com
        - https://www.admin.techytechster.com
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid
      ClientName: AdminLogin
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
  AdminLoginPage:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: techytechsteradmin
      UserPoolId: !Ref AdminUserPool

Outputs:
  AdminUserPool:
    Value: !Ref AdminUserPool
  AdminLoginClient:
    Value: !Ref AdminLoginClient
  AdminLoginPage:
    Value: !Ref AdminLoginPage