name: BuildTestDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploytechytechsterstaticsite:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: Deploy Infrastructure
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: TechytechsterStaticSite
            template: ./ci/staticsite.yml
            no-fail-on-empty-changeset: "1"
  
  PublicStaticSite:
    needs: [deploytechytechsterstaticsite]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: check perms
          run: chmod +x ./ci/build.sh
        - name: BuildTestDeploy Frontend
          run: ./ci/build.sh
        - name: Fix File Extensions
          run: |
            chmod +x ./replaceHtml.sh
            ./replaceHtml.sh
        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: techytechster
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
            SOURCE_DIR: './build'      # optional: defaults to entire repository
        - name: invalidate
          uses: chetan/invalidate-cloudfront-action@master
          env:
            DISTRIBUTION: E3E1R8A8AGLES3
            PATHS: '/index.html'
            AWS_REGION: 'ap-southeast-2'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}