name: BuildTestDeploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploytechytechsterstaticsite:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: Deploy Infrastructure
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: TechytechsterStaticSite
            template: ./ci/TechytechsterStaticSite.yaml
            no-fail-on-empty-changeset: "1"

  deployadminstaticsite:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: Deploy Infrastructure
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: AdminStaticSite
            template: ./ci/Admin.yaml
            no-fail-on-empty-changeset: "1"
  
  deployauthentication:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: Deploy Infrastructure
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: Authentication
            template: ./ci/Authentication.yaml
            no-fail-on-empty-changeset: "1"
  
  deploymisc:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: Deploy Infrastructure
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: MiscStack
            template: ./ci/Misc.yaml
            no-fail-on-empty-changeset: "1"
  

  # This workflow contains a single job called "build"
  PublicStaticSite:
    needs: [deploytechytechsterstaticsite, deployadminstaticsite, deployauthentication, deploymisc]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: check perms
          run: chmod +x ./ci/BuildTestDeployTechytechsterFrontend.sh
        - name: BuildTestDeploy Frontend
          run: ./ci/BuildTestDeployTechytechsterFrontend.sh
        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: techytechster
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
            SOURCE_DIR: './techytechsterfrontend/build'      # optional: defaults to entire repository
        - name: invalidate
          uses: chetan/invalidate-cloudfront-action@master
          env:
            DISTRIBUTION: E2SUFRIG593PJV
            PATHS: '/index.html'
            AWS_REGION: 'ap-southeast-2'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  AdminStaticSite: # CHANGE BuildTestDeployTechytechsterFrontend.sh
    needs: [deploytechytechsterstaticsite, deployadminstaticsite, deployauthentication, deploymisc]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Configure AWS credentials
          id: creds
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
        - name: check perms
          run: chmod +x ./ci/BuildTestDeployAdminSite.sh
        - name: BuildTestDeploy Frontend
          run: ./ci/BuildTestDeployAdminSite.sh
        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: admin.techytechster
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
            SOURCE_DIR: './adminfrontend/build'      # optional: defaults to entire repository
        - name: invalidate
          uses: chetan/invalidate-cloudfront-action@master
          env:
            DISTRIBUTION: E2SUFRIG593PJV
            PATHS: '/index.html'
            AWS_REGION: 'ap-southeast-2'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  APITechytechster:
    needs: [deploytechytechsterstaticsite, deployadminstaticsite, deployauthentication, deploymisc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: check perms
        run: chmod +x ./ci/BuildAPI.sh
      - name: Build API And Deploy
        run: ./ci/BuildAPI.sh